jwt:
  secret:
    key: ${JWT_SECRET_KEY}
server:
  port: 8080
  shutdown: graceful
  graceful:
    shutdown:
      timeout: 30s


spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: dachaerowa


  datasource:
    url: jdbc:mysql://${DATABASE_URL}/dachaerowa?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
    hikari:
      maximum-pool-size: 10


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: info
    org.springframework.web: debug


---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DATABASE_URL}/dachaerowa?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
  jpa:
    hibernate:
      ddl-auto: create-drop


---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DATABASE_URL}/dachaerowa?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
  jpa:
    hibernate:
      ddl-auto: none
